### PR TITLE
Update phystrix dependency

### PR DESCRIPTION
**Pull request by acanimal**
I found problems when using physxtrix@2 in my project.

### CODE REVIEW

**Comment by lcf** [comment]
@acanimal what kind of problems?

**Comment by acanimal** [comment]
Its about depencies. I tried to use it in a project with phystrix v2 and when adding phystrix-dashboard composer fails because it depends on phyxtrix v1.

**Comment by lcf** [comment]
@acanimal I see, thank you. We never package the dashboard inside an application where Phystrix is used, I would recommend you making sure it makes sense for you.

However, your request makes perfect sense. The only thing is, would you mind updating the version constraint in your PR in a way that both 1.*.* and 2.*.* are allowed? whichever is available

**Comment by acanimal** [comment]
Done.

I was working on an example on how to use phystrix. Anyway your note about using phystrix-dashboard inside the main app is a good point.

Cheers

**Comment by acanimal** [comment]
Done

**Comment by lcf** [comment]
I'm getting this when trying to 'composer install'

[UnexpectedValueException]                                              
  Could not parse version constraint >=1.*: Invalid version string "1.*" 

to avoid going back and forth I fixed it in master myself, please checkout release 1.0.2. I hope this works for you and thank you for bringing up the issue.

**Pull request closed without merging**
